### ISSUE TITLE
Running UCE on new species

### ISSUE THREAD

**Issue by PeterZZQ** [snap-stanford/UCE#52]
Hi, I'm trying to run UCE on Marmoset dataset, but the species is not included in the UCE data. I have obtained the protein embedding using ESM2 (36 layers) and the chromosome location of genes in marmoset, but I noticed that there is also a `offset` file. How am I supposed to give the value for the offset of marmoset?  And do I need to modify other files too?

**Comment by PeterZZQ** [comment]
I'm able to update `offset` file to be the shift of embedding index of new species, but when I run the code, the following issue is reported

```
Using sample 4 layer model
Proccessing Marmoset_M1_10xV3
2294.0
Marmoset_M1_10xV3 (69279, 13473)
Wrote Shapes Dict
13473
Max Code: 715
Loaded model:
./model_files/4layer_model.torch
  0%|                                                                                                                                                                                                                                                                                                                                                                                                                               
Traceback (most recent call last):
  File "/net/csefiles/xzhanglab/shared/UCE/eval_single_anndata.py", line 156, in <module>
    main(args, accelerator)
  File "/net/csefiles/xzhanglab/shared/UCE/eval_single_anndata.py", line 85, in main
    processor.run_evaluation()
  File "/net/csefiles/xzhanglab/shared/UCE/evaluate.py", line 153, in run_evaluation
    run_eval(self.adata, self.name, self.pe_idx_path, self.chroms_path,
  File "/net/csefiles/xzhanglab/shared/UCE/evaluate.py", line 250, in run_eval
    batch_sentences = nn.functional.normalize(batch_sentences,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nethome/zzhang834/miniconda3/envs/UCE/lib/python3.11/site-packages/torch/nn/functional.py", line 4719, in normalize
    denom = input.norm(p, dim, keepdim=True).clamp_min(eps).expand_as(input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nethome/zzhang834/miniconda3/envs/UCE/lib/python3.11/site-packages/torch/_tensor.py", line 708, in norm
    return torch.norm(self, p, dim, keepdim, dtype=dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nethome/zzhang834/miniconda3/envs/UCE/lib/python3.11/site-packages/torch/functional.py", line 1611, in norm
    return torch.linalg.vector_norm(input, _p, _dim, keepdim, dtype=dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
May I know how to fix it? Thanks.

**Comment by Yanay1** [comment]
Hi, UCE requires using the full 15b esm2 model, not the 36 layer 3b model. 

What command are you using to launch UCE for the new species?

**Comment by PeterZZQ** [comment]
Yes, I noticed that because the protein dimensions didn't match, and have updated the protein embedding 15b esm2 model. The command I used is as follows:
```bash
adata_path="/project/shared/UCE/marmoset_m1/Marmoset_M1_10xV3.h5ad"
dir="marmoset_m1/"
species="zzmarmoset"
spec_chrom_csv_path="/project/shared/UCE/model_files/species_chrom_wmarmoset.csv"
token_file="/project/shared/UCE/model_files/all_tokens_marmoset.torch"
offset_path="/project/shared/UCE/model_files/species_offsets_wmarmoset.pkl"

batch_size="50"

python eval_single_anndata.py --adata_path ${adata_path} --dir ${dir} --species ${species} --batch_size ${batch_size} --spec_chrom_csv_path ${spec_chrom_csv_path} --token_file ${token_file} --offset_pkl_path ${offset_path}

``` 
the `spec_chrom_csv_path` file is self-generated with the chromosome id and starting location of gene region. I updated the original token files to include the protein embedding and randomly generated chromosome embedding of new species (which changes the total dimension of token embedding from 145469 to 159015). the offset file is updated accordingly. In the script `evaluation.py`, there are several hard-coded 145469 values, I updated them all to 159015 according to the new token dimensions.

**Comment by qsimeon** [comment]
I am also trying to apply UCE to a new species - C. elegans. Specifically I was trying to run it on this h5ad file: https://data.caltech.edu/records/c6r3r-csp77/files/bendavid2021.h5ad?download=1

`!python eval_single_anndata.py --adata_path ../bendavid2021.h5ad --dir ../output --species human --batch_size 100`


I got this error:
```
Using sample 4 layer model
Proccessing bendavid2021
Traceback (most recent call last):
  File "/content/uce/eval_single_anndata.py", line 155, in <module>
    main(args, accelerator)
  File "/content/uce/eval_single_anndata.py", line 83, in main
    processor.preprocess_anndata()
  File "/content/uce/evaluate.py", line 94, in preprocess_anndata
    process_raw_anndata(self.row,
  File "/content/uce/data_proc/data_utils.py", line 211, in process_raw_anndata
    dataset, adata = anndata_to_sc_dataset(ad, species=species, labels=labels, covar_col=covar_col, hv_genes=None)
  File "/content/uce/data_proc/data_utils.py", line 123, in anndata_to_sc_dataset
    adata, protein_embeddings = load_gene_embeddings_adata(
  File "/content/uce/data_proc/gene_embeddings.py", line 73, in load_gene_embeddings_adata
    species_to_gene_embeddings = {
  File "/content/uce/data_proc/gene_embeddings.py", line 74, in <dictcomp>
    species_name: torch.stack([
RuntimeError: stack expects a non-empty TensorList
```

**Comment by qsimeon** [comment]
When you say "Please also add this line to the dictionary created on line 247 in the file `data_proc/data_utils.py`." in section ###Example evaluation of new species of the `Create New Species Files.ipynb` notebook, I think you meant add it to the dictionary created on line 13 in the `data_proc/gene_embeddings.py` (i.e. in `MODEL_TO_SPECIES_TO_GENE_EMBEDDING_PATH`) because the `embeddings_paths` dictionary in `data_proc/data_utils.py` gets updated already with the code on line 258.

**Comment by Yanay1** [comment]
I think line 247 in the notebook as stated is correct, could you let me know if you still weren't able to run this?
